# Purpose: The standard install.yaml configures permissions for the workflow controller, but does
# not configure permissions for the service accounts that workflow pods run as. Without these
# permissions, the executor will fall back to the legacy insecure pod patch method, which requires
# broader permissions and is a security risk. This step grants the default service account (used by
# workflow pods unless otherwise specified) the minimal permissions needed to create and update
# workflowtaskresults. If you use custom service accounts in your workflows, you'll need to create
# additional RoleBindings for those accounts as well.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor # can be any name as long as it matches the rolebinding
  namespace: argo
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-default
  namespace: argo
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor # can be any name as long as it matches the role
