apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: automate-metashape-workflow-
spec:
  serviceAccountName: argo
  entrypoint: main

  # Ensure that by default, workflow pods are scheduled on non-GPU nodes. Will need to override for
  # GPU tasks with podSpecPatch: ""
  podSpecPatch: |
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia.com/gpu
                  operator: DoesNotExist

  # A list of input parameters available to the workflow at runtime. 
  # These parameters can be referenced throughout the workflow templates using {{workflow.parameters.<name>}}
  arguments:
    parameters:
      - name: CONFIG_LIST
        default: "config_list.txt"
      - name: RUN_FOLDER
        default: "default-run"
      # S3 / rclone upload parameters
      - name: S3_BUCKET
        default: ""
      # Post-processing parameters
      - name: S3_BUCKET_OUTPUT
        default: "ofo-public"
      - name: OUTPUT_DIRECTORY
        default: ""
      - name: BOUNDARY_DIRECTORY
        default: ""
      - name: WORKING_DIR
        default: "/tmp/processing"
      #- name: OUTPUT_MAX_DIM
        #default: "800"

  # Defining where to read raw drone imagery data and write out imagery products to `/ofo-share`
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ceph-share-rw-pvc2

  templates:
    # the 'main' template defines the order of high-level steps to be completed in the workflow. 
    # the 'process-datasets' step has a looping directive (withParam) which goes through each dataset name and processes it.
    - name: main
      steps:
        - - name: determine-datasets
            template: determine-datasets
        - - name: process-datasets
            template: process-dataset-workflow
            arguments:
              parameters:
                - name: dataset-name
                  value: "{{item.name}}"
                - name: config-file
                  value: "{{item.config_file}}"
            withParam: "{{steps.determine-datasets.outputs.result}}"

    ## Here we define what the main steps actually do

    # Use containerized python to parse through the list of datasets as specified from runtime parameter 'CONFIG_LIST'
    # outputs a json of dataset names that is passed to the next steps
    - name: determine-datasets
      script:
        image: python:3.9
        volumeMounts:
          - name: data
            mountPath: /input
            subPath: "argo-input/{{workflow.parameters.CONFIG_LIST}}"
        command: ["python3"]
        source: |
          import json, sys, os
          with open("/input", "r") as f:
              datasets = []
              for line in f:
                  name = line.strip()
                  if name:
                      # Output dict with both full filename and basename
                      base = os.path.splitext(name)[0]
                      datasets.append({
                          "name": base,
                          "config_file": name
                      })

              # Output as JSON list
              json.dump(datasets, sys.stdout)

    # High-level order of steps in the 'process-dataset-workflow' step. Each step will be defined later.
    - name: process-dataset-workflow
      inputs:
        parameters:
          - name: dataset-name
          - name: config-file
      dag:
        tasks:
          - name: run-processing
            template: run-automate-metashape
            arguments:
              parameters:
                - name: dataset-name
                  value: "{{inputs.parameters.dataset-name}}"
                - name: config-file
                  value: "{{inputs.parameters.config-file}}"
            continueOn:
              failed: true

          # TEMPORARILY DISABLED these two blocks (up to just before logging) just for testing    
          # # As soon as processing finishes, kick off upload in parallel on any available node
          # - name: rclone-upload
          #   dependencies: [run-processing]
          #   template: rclone-upload-to-s3
          #   arguments:
          #     parameters:
          #       - name: dataset-name
          #         value: "{{inputs.parameters.dataset-name}}"

          # - name: postprocess-dataset
          #   dependencies: [rclone-upload]
          #   template: run-postprocessing
          #   arguments:
          #     parameters:
          #       - name: dataset-name
          #         value: "{{inputs.parameters.dataset-name}}"
          #   when: "{{tasks.rclone-upload.status}} == Succeeded"

    ## Here we define what each step does in 'process-dataset-workflow' step

    # Defining how to process each dataset name
    - name: run-automate-metashape
      inputs:
        parameters:
          - name: dataset-name
          - name: config-file
      # Override workflow-level CPU-only affinity; GPU resource requirement ensures GPU node scheduling
      podSpecPatch: ""
      # Use docker automate-metashape to do photogrammetry
      container:
        image: ghcr.io/open-forest-observatory/automate-metashape
        volumeMounts:
          - name: data
            mountPath: /data
        command: ["python3", "/app/python/metashape_workflow.py"]
        args:
          - "--config_file"
          - "/data/argo-input/configs/{{inputs.parameters.config-file}}"
          - "--project-path"
          - "/data/argo-output/{{workflow.parameters.RUN_FOLDER}}/{{inputs.parameters.dataset-name}}/project"
          - "--output-path"
          - "/data/argo-output/{{workflow.parameters.RUN_FOLDER}}/{{inputs.parameters.dataset-name}}/output"
          - "--run-name"
          - "{{inputs.parameters.dataset-name}}"
        resources:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        env:
          - name: AGISOFT_FLS
            valueFrom:
              secretKeyRef:
                name: agisoft-license
                key: license_server

    # --------- RCLONE UPLOAD (Docker image) ---------
    - name: rclone-upload-to-s3
      inputs:
        parameters:
          - name: dataset-name
      container:
        image: rclone/rclone:latest
        volumeMounts:
          - name: results
            mountPath: /results
            subPath: derek-test-results
        command: ["/bin/sh", "-lc"]
        args:
          - |
            set -euo pipefail
            SRC="/results/{{workflow.parameters.RUN_FOLDER}}/{{inputs.parameters.dataset-name}}/output/"
            SRC_parent="/results/{{workflow.parameters.RUN_FOLDER}}/{{inputs.parameters.dataset-name}}"
            DST=":s3:{{workflow.parameters.S3_BUCKET}}/{{workflow.parameters.RUN_FOLDER}}"

            echo "[rclone] Uploading $SRC -> $DST"
            rclone copy "$SRC" "$DST" \
              --s3-provider "$RCLONE_S3_PROVIDER" \
              --s3-endpoint "$RCLONE_S3_ENDPOINT" \
              --s3-access-key-id "$RCLONE_S3_ACCESS_KEY_ID" \
              --s3-secret-access-key "$RCLONE_S3_SECRET_ACCESS_KEY" \
              --transfers 8 --checkers 8 --retries 5 --retries-sleep=15s \
              --s3-upload-cutoff 200Mi --s3-chunk-size 100Mi --s3-upload-concurrency 4 \
              --stats 15s --stats-log-level NOTICE

            echo "[rclone] Upload complete. "

            # Check if upload was successful
            if [ $? -eq 0 ]; then
              echo "[rclone] Upload successful for {{inputs.parameters.dataset-name}}"
          
              # Clean up local files after successful upload
              echo "[cleanup] Removing local files after successful upload..."
              if [ -d "$SRC_parent" ]; then
                rm -rf "$SRC_parent"
                echo "[cleanup] Successfully removed: $SRC_parent"
              else
                echo "[cleanup] Source directory not found: $SRC_parent"
              fi
            else
              echo "[rclone] Upload failed for {{inputs.parameters.dataset-name}}"
              echo "[cleanup] Keeping local files due to upload failure"
              exit 1
            fi

            echo "[rclone] Upload and cleanup completed for {{inputs.parameters.dataset-name}}"

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            memory: "1Gi"
        env:
          - name: RCLONE_S3_PROVIDER
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: provider
          - name: RCLONE_S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: endpoint
          - name: RCLONE_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: access_key
          - name: RCLONE_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: secret_key

    #--------- POST-PROCESSING (Python Docker image) ---------
    - name: run-postprocessing
      inputs:
        parameters:
          - name: dataset-name
      container:
        image: ghcr.io/open-forest-observatory/photogrammetry-postprocess:1.7
        env:
          - name: S3_PROVIDER
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: provider
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: endpoint
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: access_key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: secret_key
          - name: S3_BUCKET_INPUT_DATA
            value: "{{workflow.parameters.S3_BUCKET}}"
          - name: INPUT_DATA_DIRECTORY
            value: "{{workflow.parameters.RUN_FOLDER}}"
          - name: DATASET_NAME
            value: "{{inputs.parameters.dataset-name}}"
          - name: S3_BUCKET_INPUT_BOUNDARY
            value: "{{workflow.parameters.S3_BUCKET_OUTPUT}}"
          - name: INPUT_BOUNDARY_DIRECTORY
            value: "{{workflow.parameters.BOUNDARY_DIRECTORY}}"
          - name: S3_BUCKET_OUTPUT
            value: "{{workflow.parameters.S3_BUCKET_OUTPUT}}"
          - name: OUTPUT_DIRECTORY
            value: "{{workflow.parameters.OUTPUT_DIRECTORY}}"
          #- name: OUTPUT_MAX_DIM
            #value: "{{workflow.parameters.OUTPUT_MAX_DIM}}"
          - name: WORKING_DIR
            value: "{{workflow.parameters.WORKING_DIR}}"
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
