apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: detect-trees-workflow-
spec:
  serviceAccountName: argo
  entrypoint: main

  # Set imagePullPolicy for all containers in the workflow
  podSpecPatch: |
    containers:
      - name: main
        imagePullPolicy: Always

  # Affinity rules for workflow pods:
  # 1. nodeAffinity: Schedule on non-GPU nodes by default (GPU tasks override with affinity: {})
  # 2. podAffinity: Prefer nodes with other running workflow pods to minimize autoscaler evictions
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: DoesNotExist
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: workflows.argoproj.io/completed
                  operator: In
                  values:
                    - "false"
            topologyKey: kubernetes.io/hostname

  # A list of input parameters available to the workflow at runtime.
  # These parameters can be referenced throughout the workflow templates using {{workflow.parameters.<name>}}
  arguments:
    parameters:
      - name: CAMERAS_FILE
      - name: MESH_FILE
      - name: DTM_FILE
      - name: IMAGE_FOLDER
      - name: CHM_FILE
      - name: OUTPUT_FOLDER
      - name: MESH_CRS
        value: 26910
      - name: CHIP_SIZE
        value: 4000
      - name: CHIP_STRIDE
        value: 3600

  # Defining where to read raw drone imagery data and write out imagery products to `/ofo-share`
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ceph-share-rw-pvc2

  templates:
    # the 'main' template defines the order of high-level steps to be completed in the workflow.
    # the 'process-datasets' step has a looping directive (withParam) which goes through each dataset name and processes it.
    - name: main
      steps:
        - - name: detect-trees
            template: detect-trees
            arguments:
              parameters:
                 - name: chm-file
                   value: "{{workflow.parameters.CHM_FILE}}"
                 - name: detected-trees-file
                   value: "{{workflow.parameters.OUTPUT_FOLDER}}/detected_trees.gpkg"
        - - name: render-instance-labels
            template: render-instance-labels
            arguments:
              parameters:
                 - name: mesh-file
                   value: "{{workflow.parameters.MESH_FILE}}"
                 - name: cameras-file
                   value: "{{workflow.parameters.CAMERAS_FILE}}"
                 - name: dtm-file
                   value: "{{workflow.parameters.DTM_FILE}}"
                 - name: trees-file
                   value: "{{workflow.parameters.OUTPUT_FOLDER}}/detected_trees.gpkg"
                 - name: mesh-crs
                   value: "{{workflow.parameters.MESH_CRS}}"
                 - name: image-folder
                   value: "{{workflow.parameters.IMAGE_FOLDER}}"
                 - name: render-savefolder
                   value: "{{workflow.parameters.OUTPUT_FOLDER}}/renders"

    - name: detect-trees
      inputs:
        parameters:
          - name: chm-file
          - name: detected-trees-file
      container:
        image: ghcr.io/open-forest-observatory/tree-detection-framework:feature-dr-containerize
        volumeMounts:
          - name: data
            mountPath: /data
        command: [
                  "python",
                  "-m",
                  "tree_detection_framework.entrypoints.generate_predictions",
                  "--raster-folder-path",
                  "{{inputs.parameters.chm-file}}",
                  "--tree-detection-model",
                  "geometric",
                  "--predictions-save-path",
                  "{{inputs.parameters.detected-trees-file}}",
                  "--chip-size",
                  "{{workflow.parameters.CHIP_SIZE}}",
                  "--chip-stride",
                  "{{workflow.parameters.CHIP_STRIDE}}"
                ]
    - name: render-instance-labels
      inputs:
        parameters:
          - name: mesh-file
          - name: cameras-file
          - name: dtm-file
          - name: trees-file
          - name: mesh-crs
          - name: image-folder
          - name: render-savefolder
      container:
        image: ghcr.io/open-forest-observatory/geograypher:feature-dr-containerize
        volumeMounts:
          - name: data
            mountPath: /data
        command: ["python",
            "-m", "geograypher.entrypoints.render_labels",
            "--mesh-file", "{{inputs.parameters.mesh-file}}",
            "--mesh-CRS", "{{inputs.parameters.mesh-crs}}",
            "--cameras-file", "{{inputs.parameters.cameras-file}}",
            "--texture", "{{inputs.parameters.trees-file}}",
            "--DTM-file", "{{inputs.parameters.dtm-file}}",
            "--image-folder", "{{inputs.parameters.image-folder}}",
            "--render-savefolder", "{{inputs.parameters.render-savefolder}}",
            "--texture-column-name", "unique_ID",
            "--ground-height-threshold", "2.0"]
